name: Mirror to GitLab

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_MATAELANG_TOKEN }}
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.mataelang.net/default/ui.git"
          if [ "${{ github.event_name }}" == "release" ]; then
            TAG="${{ github.event.release.tag_name }}"
            git push gitlab "${TAG}"
          else
            git push gitlab main
          fi
